### PR TITLE
Implement support for Array properties

### PR DESCRIPTION
**Pull request by ArondeParon**
# What does this pull request fix?

Laravel Scout has built-in support for array properties, but the array driver (ironically 😝 ) does not support searching properties with array values.

This pull request implements support for simple, flat arrays and will allow you to index and search models like this:

```php
public function toSearchableArray(): array
{
    return [
        'id' => $this->id,
        'categories' => [5, 6, 7]
    ];
}
```

**Searching:**

```php
$model->search()->where('category', 6);
```

### CODE REVIEW

**Comment by Sti3bas** [comment]
@ArondeParon hmm, what is your use case? Maybe you could share your real world example?

**Comment by ArondeParon** [comment]
@Sti3bas my use case is similar to the description of this issue: I have certain fields that contain more than one property value. For example, a product that can have more than one category attached to it.

ElasticSearch natively handles array properties by searching each value, but the array driver does not seem to support this.

**Comment by Sti3bas** [comment]
@ArondeParon it seems like your test depends on search implementation of the driver, if I understand you correctly. I think you should avoid that, because all these (ElasticSearch, MeiliSearch, Algolia etc.) drivers might return different results for the same query. You should only focus on testing your app's logic and all search results should be mocked.

Array driver was never intended to replicate search functionality of other drivers.

**Comment by ArondeParon** [comment]
Fair enough. I have switched to integration testing to test my logic, so this use case is no longer required for me.

**Pull request closed without merging**
